### ISSUE TITLE
SSLCertVerificationError: vehicle_info.py

### ISSUE THREAD

**Issue by tht2020** [nshp/python-lucidmotors#4]
I can't login successfully via python or via the integration in HA. The integration was previously working. 

 File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host mobile.deneb.prod.infotainment.pdx.atieva.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

**Comment by nshp** [comment]
Wild theory, but check the clock on the machine where you're running HA? It's saying the SSL certificate is invalid. That certificate currently expires on December 12th. If you clock got badly out of sync that could explain it.

**Comment by tht2020** [comment]
It looks like it might be something with my account. The curl worked and no issues. My MBPro clock is up to date. The same SSL error came back when I entered a null password to test.

**Comment by nshp** [comment]
Very weird. I get an actual error message back (`Login call failed.invalid loginID or password`) for invalid creds. I'd say give it a day to see if there's just a problem on Lucid's end, but do let us know if it doesn't resolve itself.

**Comment by tht2020** [comment]
I just reenabled Passive Lock, reset the HA integration, and reauthenticated successfully. Embarrassingly, it must be something with my local environment. I had disabled passive lock earlier in the day and that is what broke the HA integration. 

Any MacOS Python cleanup/reinstall guides you can recommend lol? ;)
