### ISSUE TITLE
Set sensor.<name>_speed to imperial

### ISSUE THREAD

**Issue by tht2020** [nshp/python-lucidmotors#8]
Currently this displays by default the Speed as km/h.

**Comment by nshp** [comment]
Fixed over in https://github.com/borski/ha-lucidmotors/commit/970cebd2384827da996ec7bf1a660496883d8863
This won't override your speed unit if you have an existing install, but you can change it by clicking the Speed sensor, then the gear icon, and selecting mph as your unit.
